default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: posts_api_development

test:
  <<: *default
  database: posts_api_test

production:
  <<: *default
  database: posts_api_production
  username: posts_api
  password: <%= ENV["POSTS_API_DATABASE_PASSWORD"] %>
