name: Run k6 Load Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Snap
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install core

      - name: Install k6 via Snap
        run: |
          sudo snap install k6

      - name: Run k6 Load Tests
        run: |
          k6 run script.js