name: Run k6 Load Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        uses: sourceryai/setup-postgresql-action@v1
        with:
          postgresql version: '16'
          postgresql db: 'posts_api_test'
          postgresql user: 'posts_api'
          postgresql password: 'password'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Prepare Database
        env:
          PGUSER: posts_api
          PGPASSWORD: password
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails db:seed

      - name: Start Rails Server
        run: |
          bundle exec rails server -e test -p 3000 -d

      - name: Wait for Server to Start
        run: sleep 10

      - name: Install Snap and k6
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install core
          sudo snap install k6

      - name: Run k6 Load Tests
        run: |
          k6 run script.js
