name: Run k6 Load Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run k6 Load Tests
        run: |
          k6 run --out json=output.json test/load_test.js
